In [1]:
import pandas as pd

df = pd.read_csv("IRIS.csv")
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [2]:
df.shape

(150, 5)

In [3]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [4]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
df[(df["petal_length"] > 4.5) & (df["species"] == "Iris-virginica")]

     sepal_length  sepal_width  petal_length  petal_width         species
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica
104           6.5          3.0           5.8          2.2  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
107           7.3          2.9           6.3          1.8  Iris-virginica
108           6.7          2.5           5.8          1.8  Iris-virginica
109           7.2          3.6           6.1          2.5  Iris-virginica
110           6.5          3.2           5.1          2.0  Iris-virginica
111           6.4          2.7           5.3          1.9  Iris-virginica
112           6.8          3.0           5.5          2.1  Iris-virginica
113           5.7          2.5           5.0          2.0  Iris-virginica
114           5.8          2.8           5.1          2.4  Iris-virginica
115           6.4          3.2           5.3          2.3  Iris-virginica
116           6.5          3.0           5.5          1.8  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
119           6.0          2.2           5.0          1.5  Iris-virginica
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [6]:

df.groupby("species")[["sepal_length"]].agg("mean")

                 sepal_length
species
Iris-setosa             5.006
Iris-versicolor         5.936
Iris-virginica          6.588

In [7]:
df.groupby("species")[["petal_width"]].agg("max")

                 petal_width
species
Iris-setosa              0.6
Iris-versicolor          1.8
Iris-virginica           2.5

In [8]:
df.groupby("species")[["sepal_width"]].agg("std")

                 sepal_width
species
Iris-setosa         0.381024
Iris-versicolor     0.313798
Iris-virginica      0.322497

In [9]:
df.groupby('species').agg({
    'sepal_length': 'mean',
    'petal_width': 'max',
    'sepal_width': 'std'
})

                 sepal_length  petal_width  sepal_width
species
Iris-setosa             5.006          0.6     0.381024
Iris-versicolor         5.936          1.8     0.313798
Iris-virginica          6.588          2.5     0.322497

In [12]:
df["petal_ratio"] = df["petal_length"] / df["petal_width"]
df

,sepal_length,sepal_width,petal_length,petal_width,species,petal_ratio
0,5.1,3.5,1.4,0.2,Iris-setosa,7.000000
1,4.9,3.0,1.4,0.2,Iris-setosa,7.000000
2,4.7,3.2,1.3,0.2,Iris-setosa,6.500000
3,4.6,3.1,1.5,0.2,Iris-setosa,7.500000
4,5.0,3.6,1.4,0.2,Iris-setosa,7.000000
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,2.833333

In [14]:
df.groupby("species")[["petal_ratio"]].agg("std")

                 petal_ratio
species
Iris-setosa         3.123779
Iris-versicolor     0.312456
Iris-virginica      0.407367

In [16]:
df = pd.read_csv("Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
new_df = df[["Name", "Sex", "Age","Fare","Survived"]]
new_df

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,13.0000,0
887,"Graham, Miss. Margaret Edith",female,19.0,30.0000,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.4500,0
889,"Behr, Mr. Karl Howell",male,26.0,30.0000,1
890,"Dooley, Mr. Patrick",male,32.0,7.7500,0

In [18]:
new_df[(new_df["Sex"] == "female") & (new_df["Fare"] > 30)]

,Name,Sex,Age,Fare,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,30.0708,1
25,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,31.3875,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,146.5208,1
...,...,...,...,...,...
853,"Lines, Miss. Mary Conover",female,16.0,39.4000,1
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,164.8667,1
863,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,69.5500,0
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,52.5542,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,83.1583,1

In [19]:
df.groupby("Pclass").agg({
    "Survived":"mean",
    "Fare":"mean",
    "Age":"mean"
})

        Survived       Fare        Age
Pclass
1       0.629630  84.154687  38.233441
2       0.472826  20.662183  29.877630
3       0.242363  13.675550  25.140620